spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring_boot_mongo_app
#      mongod --dbpath /usr/local/var/mongodb --logpath /usr/local/var/log/mongodb/mongo.log --fork
server:
  port: 8081